version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Sanjay20378
      POSTGRES_DB: curvvtech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: DATABASE_URL=postgres://user:Sanjay20378@localhost:5432/curvvtech_db
      JWT_SECRET: your_super_secure_and_long_jwt_secret_key
      RATE_LIMIT_MINUTES: 1
      RATE_LIMIT_MAX_REQUESTS: 100
    depends_on:
      - db
    command: npm run start

volumes:
  postgres-data: