version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: curvvtech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/curvvtech_db
      JWT_SECRET: your_super_secret_jwt_key
      RATE_LIMIT_MIN: 1
      RATE_LIMIT_MAX: 100
    depends_on:
      - db
    command: npm run start

volumes:
  postgres-data: